-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keep class com.google.android.gms.measurement.AppMeasurement { *; }
-keep class com.google.android.gms.measurement.AppMeasurementOnEventListener { *; }